(:name           "debian")
(:repo           "taffish-org/debian")
(:author         "KaiyuanHan")
(:version        "12")
(:intro          "Debian (/ˈdɛbiən/), also known as Debian GNU/Linux, is a free and open source Linux distribution, developed by the Debian Project, which was established by Ian Murdock in August 1993. Debian is one of the oldest operating systems based on the Linux kernel, and is the basis of many other Linux distributions.")
(:dependencies)
(:functions      "[default debian 12]")
